DEVICE          : cuda              # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : '/data/naman_deep_singh/model_zoo/seg_models'         # output folder name used for saving the model, logs and inference results

MODEL:                                    
  NAME          : UperNet                                           # name of the model you are using
  BACKBONE      : ConvNeXt-T                                                  # model variant
  PRETRAINED    : '/data/naman_deep_singh/model_zoo/clean/convnext_tiny_1k_224_ema.pth'              # backbone model's weight 

DATASET:
  NAME          : ADE20K                                              # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : '/data/naman_deep_singh/datasets'                         # dataset root path
  IGNORE_LABEL  : -1
  N_CLS         : 150
  SEED          : 0

TRAIN:
  IMAGE_SIZE    : [512, 512]      # training image size in (h, w)
  BATCH_SIZE    : 32               # batch size used to train
  EPOCHS        : 200             # number of epochs to train
  EVAL_INTERVAL : 32              # evaluation interval during training
  AMP           : false           # use AMP in training
  DDP           : true           # use DDP training

LOSS:
  NAME          : CrossEntropy          # loss function name (ohemce, ce, dice)
  CLS_WEIGHTS   : false            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.0001            # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer 

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 1.0             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.00001             # warmup ratio
  

EVAL:
  MODEL_PATH    : 'checkpoints/pretrained/segformer/segformer.b2.ade.pth'  # trained model file path
  IMAGE_SIZE    : [512, 512]                                                            # evaluation image size in (h, w)                       
  MSF: 
    ENABLE      : false                                                                 # multi-scale and flip evaluation  
    FLIP        : true                                                                  # use flip in evaluation  
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]                                     # scales used in MSF evaluation                


# TEST:
#   MODEL_PATH    : 'checkpoints/pretrained/segformer/segformer.b2.ade.pth'  # trained model file path
#   FILE          : 'assests/ade'                                                         # filename or foldername 
#   IMAGE_SIZE    : [512, 512]                                                            # inference image size in (h, w)
#   OVERLAY       : true                                                                  # save the overlay result (image_alpha+label_alpha)