DEVICE          : cuda              # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : '/data/naman_deep_singh/model_zoo/seg_models'         # output folder name used for saving the model, logs and inference results
ADDENDUM        : 'CLEAN_CVST_MOD'

MODEL:                                    
  NAME          : UperNetForSemanticSegmentation                                           # name of the model you are using
  BACKBONE      : ConvNeXt-T_CVST                                                  # model variant
  PRETRAINED    : '/data/naman_deep_singh/model_zoo/clean/convnext_tiny_cvst_clean.pt'              # backbone model's weight 

DATASET:
  NAME          : pascalaug                                              # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : '/data/naman_deep_singh/datasets/pascal_voc'                         # dataset root path
  IGNORE_LABEL  : -1
  N_CLS         : 21
  SEED          : 0

TRAIN:  
  BASE_SIZE     : 512
  IMAGE_SIZE    : [473, 473]      # training image size in (h, w)  
  BATCH_SIZE    : 36                 # batch size used to train
  EPOCHS        : 50             # number of epochs to train
  EVAL_INTERVAL : 32              # evaluation interval during training
  ADVERSARIAL   : true
  ATTACK        : pgd
  EPS           : 4
  N_ITERS       : 2
  FREEZE        : false
  AMP           : false           # use AMP in training
  DDP           : true           # use DDP training

LOSS:
  NAME          : CrossEntropy          # loss function name (ohemce, ce, dice)
  CLS_WEIGHTS   : false            # use class weights in loss calculation

OPTIMIZER:
  NAME          : AdamW           # optimizer name
  LR            : 0.001           # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer 

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 1.0             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.00001             # warmup ratio
  

EVAL:
  NAME          : pascalvoc   
  BACKBONE      : ConvNeXt-T_CVST_ROB      
  MODEL_PATH    : '/data/naman_deep_singh/model_zoo/seg_models/pascalaug/UperNetForSemanticSegmentation_ConvNeXt-T_CVST_adv_True_2023-04-28-12_00_56_FREEZE_False_pgd_CLEAN_CVST_MOD/best_model_ckpt.pth'  # trained model file path
  BASE_SIZE     : 512
  IMAGE_SIZE    : [473, 473]                 
  BATCH_SIZE    : 16                                                                       # evaluation image size in (h, w)                       
  MSF: 
    ENABLE      : false                                                                 # multi-scale and flip evaluation  
    FLIP        : true                                                                  # use flip in evaluation  
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]                                     # scales used in MSF evaluation                


# TEST:
#   MODEL_PATH    : 'checkpoints/pretrained/segformer/segformer.b2.ade.pth'  # trained model file path
#   FILE          : 'assests/ade'                                                         # filename or foldername 
#   IMAGE_SIZE    : [512, 512]                                                            # inference image size in (h, w)
#   OVERLAY       : true                                                                  # save the overlay result (image_alpha+label_alpha)



#clean cvst model : /data/naman_deep_singh/model_zoo/seg_models/standard_logs/pascalaug/UperNetForSemanticSegmentation_ConvNeXt-T_CVST_adv_False_2023-04-22-12_47_20_CLEAN_CVST_MOD_FREEZE_False_apgd/best_model_ckpt.pth
#clean init 2-pgd: '/data/naman_deep_singh/model_zoo/seg_models/pascalaug/UperNetForSemanticSegmentation_ConvNeXt-T_CVST_adv_True_2023-04-28-12_00_56_FREEZE_False_pgd_CLEAN_CVST_MOD/best_model_ckpt.pth'
#apgd 5iter : /data/naman_deep_singh/model_zoo/seg_models/pascalaug/UperNetForSemanticSegmentation_ConvNeXt-T_CVST_ROB_adv_True_2023-04-25-12_39_29_ROBUST_CVST_MOD_FREEZE_False_apgd/best_model_ckpt.pth
#pgd 5iter : /data/naman_deep_singh/model_zoo/seg_models/standard_logs/pascalaug/UperNetForSemanticSegmentation_ConvNeXt-T_CVST_ROB_adv_True_2023-04-20-21_06_02_ROBUST_CVST_MOD_pgd_5iter/best_model_ckpt.pth
#pgd 2 iter: /data/naman_deep_singh/model_zoo/seg_models/standard_logs/pascalaug/UperNetForSemanticSegmentation_ConvNeXt-T_CVST_ROB_adv_True_2023-04-19-22_49_29_ROBUST_CVST_MOD_2_iter/best_model_ckpt.pth
#apgd 2 iter : /data/naman_deep_singh/model_zoo/seg_models/pascalaug/UperNetForSemanticSegmentation_ConvNeXt-T_CVST_ROB_adv_True_2023-04-26-21_02_33__FREEZE_False_apgdROBUST_CVST_MOD_2_ITER/best_model_ckpt.pth
#rob-init clean : /data/naman_deep_singh/model_zoo/seg_models/pascalaug/UperNetForSemanticSegmentation_ConvNeXt-T_CVST_ROB_adv_False_2023-04-30-09_16_45_FREEZE_False_apgd_ROBUST_CVST_MOD_2_ITER/best_model_ckpt